config/routes.rb
Craftbook::Application.routes.draw do
  resources :servers

  devise_for :admins

  devise_for :users

  

   root :to => 'servers#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/server.rb
class Server < ActiveRecord::Base
 attr_accessible :description, :ip, :modcomments, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @servers }
    end
  end
  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, :notice => 'Server was successfully created.' }
        format.json { render :json => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, :notice => 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38426739-1']);
  _gaq.push(['_setDomainName', 'serverbooks.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  <title>ServerBooks | MC</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://api.intercom.io/api/js/library.js';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}};})()</script>
<script id="IntercomSettingsScriptTag">
  window.intercomSettings = {
    // TODO: The current logged in user's email address.
    email: "<%= current_user.email %>",
    // TODO: The current logged in user's sign-up date as a Unix timestamp.
    created_at: <%= current_user.created_at.to_i %>,
    widget: {
    activator: '#IntercomDefaultWidget'
    },
    app_id: "b2z9bedc"
  }
</script>
<% else %>
<% end %>
<div class="row">
  <div class="twelve columns">
    <nav class="top-bar">
      <ul>
        <!-- Title Area -->
        <li class="name">
          <h1>
            <a href="http://m.serverbooks.net">
              MC ServerBooks
            </a>
          </h1>
        </li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>

          <li><a href="./servers/new">Add a Server</a></li>
          <li class="divider hide-for-small"></li>
        </ul>

        <!-- Right Nav Section -->
        <ul class="right">
          <li class="divider show-for-medium-and-up"></li>          
<li><% if user_signed_in? %><a><%= current_user.email %> is logged in. <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></a><% else %><a href="http://m.serverbooks.net/users/sign_in">Sign in or Sign Up</a><% end %></font>
        
<li class="divider show-for-medium-and-up"></li>
</ul>
      </section>
    </nav>
  </div>
</div>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :modcomments %><br />
    <%= f.text_field :modcomments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Edit the Server</h1>
<% if admin_signed_in? %>
<%= render 'form' %>
<% else %>
<h1>Good try.</h1>
<% end %>
<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<center>
<h1>Servers</h1>
<a href="#bottom">View Newest</a>
<br>
<table>
  <tr>
    <th>Server Name</th>
    <th>IP</th>
    <th>Description</th>
    <% if admin_signed_in? %>
    <th>Moderator Comments</th>
    <% else %>
    <% end %>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= truncate(server.title, :length => 25) %></td>
    <td><%= server.ip %></td>
    <td><%= truncate(server.description, :length => 75) %></td>
    <% if admin_signed_in? %>
    <td><%= server.modcomments %></td>
    <% else %>
    <% end %>
     
    <td><%= link_to 'More', server %></td>
    <% if admin_signed_in? %>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <% else %>
    <% end %>
  </tr>
<% end %>
</table>
<p id="bottom"></p>
<br />
</center>

app/views/servers/new.html.erb
<center><h1>Add a Server</h1></center>
<div class="row">
  <div class="seven columns">
<% if user_signed_in? %>   
 <%= render 'form' %>
<% else %>
<h1>Please Sign In or Register to Add Servers</h1>
<% end %>  
</div>
  <div class="five columns">
    <h1>Guidelines</h1>
    <p>There is no voting part, just yet. There are no flashy graphics or over-crowded layouts. Don't USE ALL CAPS.</p>
    <ul>
    <li>No spamming your server</li>
    <li>Every server is instantly published, but is reviewed by a moderator later on.</li>
<li>No banner images, nor any HTML</li>
<li>No "official" servers</li>
<li>No excessive profanity</li>    
</ul> 
</div>
</div>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @server.title %>
</p>

<p>
  <b>IP:</b>
  <%= @server.ip %>
</p>
  <b>Description:</b>
  <%= @server.description %>
</p>
<% if admin_signed_in? %>
<p>
  <b>Moderator Comments:</b>
  <%= @server.modcomments %>
</p>
<% else %>
<% end %>
<p>
<label>Status</label>
<iframe seamless src="http://soocialize.net/server/s.php?ip=<%= @server.ip %>">
<p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>